bin/programa: ./L50 ./L51 ./L52 ./L53 ./L54

L50:
	g++ "Ejercicio1.cpp" -o L50

L51:
	g++ "Ejercicio2.cpp" -o L51

L52:
	g++ "Ejercicio3.cpp" -o L52

L53:
	g++ "Ejercicio4.cpp" -o L53

L54:
	g++ "Ejercicio5.cpp" -o L54
